language: node_js

node_js:
#  - "0.12"
#  - "0.11"
  - "0.10"

before_script:
  - npm install grunt-cli -g
  - grunt -V
  - cat package.json
  - npm install karma-cli -g
#  - npm install karma --save-dev
  - npm install karma-jasmine --save-dev
#  - npm install karma-coverage --save-dev
#  - npm install karma-jasmine-html-reporter --save-dev
#  - npm install karma-firefox-launcher --save-dev
  - karma --version
  - cat package.json
# Set up virtual screen
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start