language: node_js

node_js:
  - "0.12"
  - "0.11"
  - "0.10"

before_script:
  - npm install grunt-cli -g
  - grunt -V
  - npm install karma-cli -g
  - karma --version
  - cat package.json
# Set up virtual screen
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

# If "script" is omitted, TravisCI will run "npm test".
# Here we explicitly run tests via both Grunt and Karma.
script:
  - npm run testGrunt
  - npm run testKarma
